name: check

permissions: {}

on:
  push:
    branches:
      - main
  pull_request:

jobs:

  types:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1

      - uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97  # v7.0.0
        with:
          python-version: '3.11'

      - uses: python/mypy@770d3ca4997032dc3a1c4f0b468e9f58e8f38505  # v1.20.0

  coverage:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1

      - uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97  # v7.0.0
        with:
          python-version: '3.11'

      - uses: actions/setup-java@b6effb05e454b25005698d916606bdc6ffcbf961  # v5.7.0
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Install package
        run: pip install coverage -e .[test]

      - name: Run tests
        run: coverage run -m pytest

      - name: Upload to Codecov.io
        uses: codecov/codecov-action@57e3a136b779b570ffcdbf80b3bdc90e7fab3de2  # v5.0.0-beta
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
